# Generated by Django 3.2.8 on 2021-11-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sys', '0005_alter_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='New_user',
        ),
    ]
