# Generated by Django 3.2.8 on 2021-11-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sys', '0009_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Order',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
