# Generated by Django 3.2.8 on 2021-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sys', '0010_auto_20211113_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ph_no',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
