# Generated by Django 3.2.8 on 2021-11-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_sys', '0011_order_ph_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ph_no',
        ),
    ]
